/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VipRouteImport } from './routes/vip'
import { Route as VaultLoginRouteImport } from './routes/vault-login'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SyndicateOverlordRouteImport } from './routes/syndicate-overlord'
import { Route as SyndicateRouteImport } from './routes/syndicate'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResellerRouteImport } from './routes/reseller'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as OgBotRouteImport } from './routes/og-bot'
import { Route as NoticeboardRouteImport } from './routes/noticeboard'
import { Route as MyGenerationsRouteImport } from './routes/my-generations'
import { Route as MusicRouteImport } from './routes/music'
import { Route as LetterhubRouteImport } from './routes/letterhub'
import { Route as JokesRouteImport } from './routes/jokes'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FormhubRouteImport } from './routes/formhub'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ConnectTelegramRouteImport } from './routes/connect-telegram'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as BossRouteImport } from './routes/boss'
import { Route as BattlehubRouteImport } from './routes/battlehub'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppealhubRouteImport } from './routes/appealhub'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BossIndexRouteImport } from './routes/boss.index'
import { Route as VipPortalsRouteImport } from './routes/vip.portals'
import { Route as TdSlugRouteImport } from './routes/td.$slug'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as StoreCatalogRouteImport } from './routes/store.catalog'
import { Route as QaHubsRouteImport } from './routes/qa.hubs'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as JokesPortalRouteImport } from './routes/jokes.portal'
import { Route as HubSlugRouteImport } from './routes/hub.$slug'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BossUsersRouteImport } from './routes/boss.users'
import { Route as BossTodoRouteImport } from './routes/boss.todo'
import { Route as BossTelegramTestRouteImport } from './routes/boss.telegram-test'
import { Route as BossTelegramSetupRouteImport } from './routes/boss.telegram-setup'
import { Route as BossStreamQueueRouteImport } from './routes/boss.stream-queue'
import { Route as BossSettingsRouteImport } from './routes/boss.settings'
import { Route as BossSecurityEventsRouteImport } from './routes/boss.security-events'
import { Route as BossSecretsInventoryRouteImport } from './routes/boss.secrets-inventory'
import { Route as BossResellerAuditRouteImport } from './routes/boss.reseller-audit'
import { Route as BossRealtimeDenialsRouteImport } from './routes/boss.realtime-denials'
import { Route as BossPublishCheckRouteImport } from './routes/boss.publish-check'
import { Route as BossPromotionsRouteImport } from './routes/boss.promotions'
import { Route as BossPricingRouteImport } from './routes/boss.pricing'
import { Route as BossPowerRouteImport } from './routes/boss.power'
import { Route as BossPortalsRouteImport } from './routes/boss.portals'
import { Route as BossPortalUsageRouteImport } from './routes/boss.portal-usage'
import { Route as BossPortalCostsRouteImport } from './routes/boss.portal-costs'
import { Route as BossOverviewRouteImport } from './routes/boss.overview'
import { Route as BossOpsRouteImport } from './routes/boss.ops'
import { Route as BossOgPassesRouteImport } from './routes/boss.og-passes'
import { Route as BossOgBotMemoryRouteImport } from './routes/boss.og-bot-memory'
import { Route as BossMembersRouteImport } from './routes/boss.members'
import { Route as BossLexiconRouteImport } from './routes/boss.lexicon'
import { Route as BossInfrastructureRouteImport } from './routes/boss.infrastructure'
import { Route as BossHubsRouteImport } from './routes/boss.hubs'
import { Route as BossFunctionIdeasRouteImport } from './routes/boss.function-ideas'
import { Route as BossFunctionGrantsRouteImport } from './routes/boss.function-grants'
import { Route as BossFunctionAuditRouteImport } from './routes/boss.function-audit'
import { Route as BossFreePurchasesRouteImport } from './routes/boss.free-purchases'
import { Route as BossDomainDenylistRouteImport } from './routes/boss.domain-denylist'
import { Route as BossDomainRouteImport } from './routes/boss.domain'
import { Route as BossDenylistAuditRouteImport } from './routes/boss.denylist-audit'
import { Route as BossControlCentreRouteImport } from './routes/boss.control-centre'
import { Route as BossContentRouteImport } from './routes/boss.content'
import { Route as BossContactsRouteImport } from './routes/boss.contacts'
import { Route as BossCommandCenterRouteImport } from './routes/boss/command-center'
import { Route as BossCivilityRouteImport } from './routes/boss.civility'
import { Route as BossAuditLogRouteImport } from './routes/boss.audit-log'
import { Route as BossApiKeysRouteImport } from './routes/boss.api-keys'
import { Route as BossAnalyticsSetupRouteImport } from './routes/boss.analytics-setup'
import { Route as BossAnalyticsRouteImport } from './routes/boss.analytics'
import { Route as BossAlertsRouteImport } from './routes/boss.alerts'
import { Route as BossAiAgentRouteImport } from './routes/boss.ai-agent'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AccountPassesRouteImport } from './routes/account.passes'
import { Route as VipPortalsHubRouteImport } from './routes/vip.portals.$hub'
import { Route as BossHubsNewRouteImport } from './routes/boss.hubs.new'
import { Route as ApiPublicSunoWebhookRouteImport } from './routes/api/public/suno-webhook'
import { Route as ApiPublicStreamM3uRouteImport } from './routes/api/public/stream-m3u'
import { Route as ApiPublic0gOrchestratorRouteImport } from './routes/api/public/0g-orchestrator'
import { Route as BossHubsIdEditRouteImport } from './routes/boss.hubs.$id.edit'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramAuthRouteImport } from './routes/api/public/telegram/auth'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTelegramRemindersRouteImport } from './routes/api/public/hooks/telegram-reminders'
import { Route as ApiPublicHooksSyndicateTickRouteImport } from './routes/api/public/hooks/syndicate-tick'
import { Route as ApiPublicFleetWebhookBotIdRouteImport } from './routes/api/public/fleet/webhook/$botId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultLoginRoute = VaultLoginRouteImport.update({
  id: '/vault-login',
  path: '/vault-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicateOverlordRoute = SyndicateOverlordRouteImport.update({
  id: '/syndicate-overlord',
  path: '/syndicate-overlord',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicateRoute = SyndicateRouteImport.update({
  id: '/syndicate',
  path: '/syndicate',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerRoute = ResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const OgBotRoute = OgBotRouteImport.update({
  id: '/og-bot',
  path: '/og-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeboardRoute = NoticeboardRouteImport.update({
  id: '/noticeboard',
  path: '/noticeboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGenerationsRoute = MyGenerationsRouteImport.update({
  id: '/my-generations',
  path: '/my-generations',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterhubRoute = LetterhubRouteImport.update({
  id: '/letterhub',
  path: '/letterhub',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesRoute = JokesRouteImport.update({
  id: '/jokes',
  path: '/jokes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FormhubRoute = FormhubRouteImport.update({
  id: '/formhub',
  path: '/formhub',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectTelegramRoute = ConnectTelegramRouteImport.update({
  id: '/connect-telegram',
  path: '/connect-telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const BossRoute = BossRouteImport.update({
  id: '/boss',
  path: '/boss',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlehubRoute = BattlehubRouteImport.update({
  id: '/battlehub',
  path: '/battlehub',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealhubRoute = AppealhubRouteImport.update({
  id: '/appealhub',
  path: '/appealhub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BossIndexRoute = BossIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BossRoute,
} as any)
const VipPortalsRoute = VipPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => VipRoute,
} as any)
const TdSlugRoute = TdSlugRouteImport.update({
  id: '/td/$slug',
  path: '/td/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCatalogRoute = StoreCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => StoreRoute,
} as any)
const QaHubsRoute = QaHubsRouteImport.update({
  id: '/qa/hubs',
  path: '/qa/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesPortalRoute = JokesPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => JokesRoute,
} as any)
const HubSlugRoute = HubSlugRouteImport.update({
  id: '/hub/$slug',
  path: '/hub/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BossUsersRoute = BossUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BossRoute,
} as any)
const BossTodoRoute = BossTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => BossRoute,
} as any)
const BossTelegramTestRoute = BossTelegramTestRouteImport.update({
  id: '/telegram-test',
  path: '/telegram-test',
  getParentRoute: () => BossRoute,
} as any)
const BossTelegramSetupRoute = BossTelegramSetupRouteImport.update({
  id: '/telegram-setup',
  path: '/telegram-setup',
  getParentRoute: () => BossRoute,
} as any)
const BossStreamQueueRoute = BossStreamQueueRouteImport.update({
  id: '/stream-queue',
  path: '/stream-queue',
  getParentRoute: () => BossRoute,
} as any)
const BossSettingsRoute = BossSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BossRoute,
} as any)
const BossSecurityEventsRoute = BossSecurityEventsRouteImport.update({
  id: '/security-events',
  path: '/security-events',
  getParentRoute: () => BossRoute,
} as any)
const BossSecretsInventoryRoute = BossSecretsInventoryRouteImport.update({
  id: '/secrets-inventory',
  path: '/secrets-inventory',
  getParentRoute: () => BossRoute,
} as any)
const BossResellerAuditRoute = BossResellerAuditRouteImport.update({
  id: '/reseller-audit',
  path: '/reseller-audit',
  getParentRoute: () => BossRoute,
} as any)
const BossRealtimeDenialsRoute = BossRealtimeDenialsRouteImport.update({
  id: '/realtime-denials',
  path: '/realtime-denials',
  getParentRoute: () => BossRoute,
} as any)
const BossPublishCheckRoute = BossPublishCheckRouteImport.update({
  id: '/publish-check',
  path: '/publish-check',
  getParentRoute: () => BossRoute,
} as any)
const BossPromotionsRoute = BossPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => BossRoute,
} as any)
const BossPricingRoute = BossPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => BossRoute,
} as any)
const BossPowerRoute = BossPowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => BossRoute,
} as any)
const BossPortalsRoute = BossPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => BossRoute,
} as any)
const BossPortalUsageRoute = BossPortalUsageRouteImport.update({
  id: '/portal-usage',
  path: '/portal-usage',
  getParentRoute: () => BossRoute,
} as any)
const BossPortalCostsRoute = BossPortalCostsRouteImport.update({
  id: '/portal-costs',
  path: '/portal-costs',
  getParentRoute: () => BossRoute,
} as any)
const BossOverviewRoute = BossOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => BossRoute,
} as any)
const BossOpsRoute = BossOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => BossRoute,
} as any)
const BossOgPassesRoute = BossOgPassesRouteImport.update({
  id: '/og-passes',
  path: '/og-passes',
  getParentRoute: () => BossRoute,
} as any)
const BossOgBotMemoryRoute = BossOgBotMemoryRouteImport.update({
  id: '/og-bot-memory',
  path: '/og-bot-memory',
  getParentRoute: () => BossRoute,
} as any)
const BossMembersRoute = BossMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => BossRoute,
} as any)
const BossLexiconRoute = BossLexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => BossRoute,
} as any)
const BossInfrastructureRoute = BossInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => BossRoute,
} as any)
const BossHubsRoute = BossHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => BossRoute,
} as any)
const BossFunctionIdeasRoute = BossFunctionIdeasRouteImport.update({
  id: '/function-ideas',
  path: '/function-ideas',
  getParentRoute: () => BossRoute,
} as any)
const BossFunctionGrantsRoute = BossFunctionGrantsRouteImport.update({
  id: '/function-grants',
  path: '/function-grants',
  getParentRoute: () => BossRoute,
} as any)
const BossFunctionAuditRoute = BossFunctionAuditRouteImport.update({
  id: '/function-audit',
  path: '/function-audit',
  getParentRoute: () => BossRoute,
} as any)
const BossFreePurchasesRoute = BossFreePurchasesRouteImport.update({
  id: '/free-purchases',
  path: '/free-purchases',
  getParentRoute: () => BossRoute,
} as any)
const BossDomainDenylistRoute = BossDomainDenylistRouteImport.update({
  id: '/domain-denylist',
  path: '/domain-denylist',
  getParentRoute: () => BossRoute,
} as any)
const BossDomainRoute = BossDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => BossRoute,
} as any)
const BossDenylistAuditRoute = BossDenylistAuditRouteImport.update({
  id: '/denylist-audit',
  path: '/denylist-audit',
  getParentRoute: () => BossRoute,
} as any)
const BossControlCentreRoute = BossControlCentreRouteImport.update({
  id: '/control-centre',
  path: '/control-centre',
  getParentRoute: () => BossRoute,
} as any)
const BossContentRoute = BossContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => BossRoute,
} as any)
const BossContactsRoute = BossContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => BossRoute,
} as any)
const BossCommandCenterRoute = BossCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => BossRoute,
} as any)
const BossCivilityRoute = BossCivilityRouteImport.update({
  id: '/civility',
  path: '/civility',
  getParentRoute: () => BossRoute,
} as any)
const BossAuditLogRoute = BossAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => BossRoute,
} as any)
const BossApiKeysRoute = BossApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => BossRoute,
} as any)
const BossAnalyticsSetupRoute = BossAnalyticsSetupRouteImport.update({
  id: '/analytics-setup',
  path: '/analytics-setup',
  getParentRoute: () => BossRoute,
} as any)
const BossAnalyticsRoute = BossAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BossRoute,
} as any)
const BossAlertsRoute = BossAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => BossRoute,
} as any)
const BossAiAgentRoute = BossAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => BossRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPassesRoute = AccountPassesRouteImport.update({
  id: '/account/passes',
  path: '/account/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const VipPortalsHubRoute = VipPortalsHubRouteImport.update({
  id: '/$hub',
  path: '/$hub',
  getParentRoute: () => VipPortalsRoute,
} as any)
const BossHubsNewRoute = BossHubsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BossHubsRoute,
} as any)
const ApiPublicSunoWebhookRoute = ApiPublicSunoWebhookRouteImport.update({
  id: '/api/public/suno-webhook',
  path: '/api/public/suno-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamM3uRoute = ApiPublicStreamM3uRouteImport.update({
  id: '/api/public/stream-m3u',
  path: '/api/public/stream-m3u',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublic0gOrchestratorRoute = ApiPublic0gOrchestratorRouteImport.update({
  id: '/api/public/0g-orchestrator',
  path: '/api/public/0g-orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const BossHubsIdEditRoute = BossHubsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => BossHubsRoute,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramAuthRoute = ApiPublicTelegramAuthRouteImport.update({
  id: '/api/public/telegram/auth',
  path: '/api/public/telegram/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramRemindersRoute =
  ApiPublicHooksTelegramRemindersRouteImport.update({
    id: '/api/public/hooks/telegram-reminders',
    path: '/api/public/hooks/telegram-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyndicateTickRoute =
  ApiPublicHooksSyndicateTickRouteImport.update({
    id: '/api/public/hooks/syndicate-tick',
    path: '/api/public/hooks/syndicate-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFleetWebhookBotIdRoute =
  ApiPublicFleetWebhookBotIdRouteImport.update({
    id: '/api/public/fleet/webhook/$botId',
    path: '/api/public/fleet/webhook/$botId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appealhub': typeof AppealhubRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/battlehub': typeof BattlehubRoute
  '/boss': typeof BossRouteWithChildren
  '/connect': typeof ConnectRoute
  '/connect-telegram': typeof ConnectTelegramRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formhub': typeof FormhubRoute
  '/history': typeof HistoryRoute
  '/jokes': typeof JokesRouteWithChildren
  '/letterhub': typeof LetterhubRoute
  '/music': typeof MusicRoute
  '/my-generations': typeof MyGenerationsRoute
  '/noticeboard': typeof NoticeboardRoute
  '/og-bot': typeof OgBotRoute
  '/portals': typeof PortalsRoute
  '/profile': typeof ProfileRoute
  '/reseller': typeof ResellerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRouteWithChildren
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vault-login': typeof VaultLoginRoute
  '/vip': typeof VipRouteWithChildren
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/account/passes': typeof AccountPassesRoute
  '/b/$slug': typeof BSlugRoute
  '/boss/ai-agent': typeof BossAiAgentRoute
  '/boss/alerts': typeof BossAlertsRoute
  '/boss/analytics': typeof BossAnalyticsRoute
  '/boss/analytics-setup': typeof BossAnalyticsSetupRoute
  '/boss/api-keys': typeof BossApiKeysRoute
  '/boss/audit-log': typeof BossAuditLogRoute
  '/boss/civility': typeof BossCivilityRoute
  '/boss/command-center': typeof BossCommandCenterRoute
  '/boss/contacts': typeof BossContactsRoute
  '/boss/content': typeof BossContentRoute
  '/boss/control-centre': typeof BossControlCentreRoute
  '/boss/denylist-audit': typeof BossDenylistAuditRoute
  '/boss/domain': typeof BossDomainRoute
  '/boss/domain-denylist': typeof BossDomainDenylistRoute
  '/boss/free-purchases': typeof BossFreePurchasesRoute
  '/boss/function-audit': typeof BossFunctionAuditRoute
  '/boss/function-grants': typeof BossFunctionGrantsRoute
  '/boss/function-ideas': typeof BossFunctionIdeasRoute
  '/boss/hubs': typeof BossHubsRouteWithChildren
  '/boss/infrastructure': typeof BossInfrastructureRoute
  '/boss/lexicon': typeof BossLexiconRoute
  '/boss/members': typeof BossMembersRoute
  '/boss/og-bot-memory': typeof BossOgBotMemoryRoute
  '/boss/og-passes': typeof BossOgPassesRoute
  '/boss/ops': typeof BossOpsRoute
  '/boss/overview': typeof BossOverviewRoute
  '/boss/portal-costs': typeof BossPortalCostsRoute
  '/boss/portal-usage': typeof BossPortalUsageRoute
  '/boss/portals': typeof BossPortalsRoute
  '/boss/power': typeof BossPowerRoute
  '/boss/pricing': typeof BossPricingRoute
  '/boss/promotions': typeof BossPromotionsRoute
  '/boss/publish-check': typeof BossPublishCheckRoute
  '/boss/realtime-denials': typeof BossRealtimeDenialsRoute
  '/boss/reseller-audit': typeof BossResellerAuditRoute
  '/boss/secrets-inventory': typeof BossSecretsInventoryRoute
  '/boss/security-events': typeof BossSecurityEventsRoute
  '/boss/settings': typeof BossSettingsRoute
  '/boss/stream-queue': typeof BossStreamQueueRoute
  '/boss/telegram-setup': typeof BossTelegramSetupRoute
  '/boss/telegram-test': typeof BossTelegramTestRoute
  '/boss/todo': typeof BossTodoRoute
  '/boss/users': typeof BossUsersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/f/$slug': typeof FSlugRoute
  '/hub/$slug': typeof HubSlugRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/qa/hubs': typeof QaHubsRoute
  '/store/catalog': typeof StoreCatalogRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/vip/portals': typeof VipPortalsRouteWithChildren
  '/boss/': typeof BossIndexRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/stream-m3u': typeof ApiPublicStreamM3uRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/boss/hubs/new': typeof BossHubsNewRoute
  '/vip/portals/$hub': typeof VipPortalsHubRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/boss/hubs/$id/edit': typeof BossHubsIdEditRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appealhub': typeof AppealhubRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/battlehub': typeof BattlehubRoute
  '/connect': typeof ConnectRoute
  '/connect-telegram': typeof ConnectTelegramRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formhub': typeof FormhubRoute
  '/history': typeof HistoryRoute
  '/jokes': typeof JokesRouteWithChildren
  '/letterhub': typeof LetterhubRoute
  '/music': typeof MusicRoute
  '/my-generations': typeof MyGenerationsRoute
  '/noticeboard': typeof NoticeboardRoute
  '/og-bot': typeof OgBotRoute
  '/portals': typeof PortalsRoute
  '/profile': typeof ProfileRoute
  '/reseller': typeof ResellerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRouteWithChildren
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vault-login': typeof VaultLoginRoute
  '/vip': typeof VipRouteWithChildren
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/account/passes': typeof AccountPassesRoute
  '/b/$slug': typeof BSlugRoute
  '/boss/ai-agent': typeof BossAiAgentRoute
  '/boss/alerts': typeof BossAlertsRoute
  '/boss/analytics': typeof BossAnalyticsRoute
  '/boss/analytics-setup': typeof BossAnalyticsSetupRoute
  '/boss/api-keys': typeof BossApiKeysRoute
  '/boss/audit-log': typeof BossAuditLogRoute
  '/boss/civility': typeof BossCivilityRoute
  '/boss/command-center': typeof BossCommandCenterRoute
  '/boss/contacts': typeof BossContactsRoute
  '/boss/content': typeof BossContentRoute
  '/boss/control-centre': typeof BossControlCentreRoute
  '/boss/denylist-audit': typeof BossDenylistAuditRoute
  '/boss/domain': typeof BossDomainRoute
  '/boss/domain-denylist': typeof BossDomainDenylistRoute
  '/boss/free-purchases': typeof BossFreePurchasesRoute
  '/boss/function-audit': typeof BossFunctionAuditRoute
  '/boss/function-grants': typeof BossFunctionGrantsRoute
  '/boss/function-ideas': typeof BossFunctionIdeasRoute
  '/boss/hubs': typeof BossHubsRouteWithChildren
  '/boss/infrastructure': typeof BossInfrastructureRoute
  '/boss/lexicon': typeof BossLexiconRoute
  '/boss/members': typeof BossMembersRoute
  '/boss/og-bot-memory': typeof BossOgBotMemoryRoute
  '/boss/og-passes': typeof BossOgPassesRoute
  '/boss/ops': typeof BossOpsRoute
  '/boss/overview': typeof BossOverviewRoute
  '/boss/portal-costs': typeof BossPortalCostsRoute
  '/boss/portal-usage': typeof BossPortalUsageRoute
  '/boss/portals': typeof BossPortalsRoute
  '/boss/power': typeof BossPowerRoute
  '/boss/pricing': typeof BossPricingRoute
  '/boss/promotions': typeof BossPromotionsRoute
  '/boss/publish-check': typeof BossPublishCheckRoute
  '/boss/realtime-denials': typeof BossRealtimeDenialsRoute
  '/boss/reseller-audit': typeof BossResellerAuditRoute
  '/boss/secrets-inventory': typeof BossSecretsInventoryRoute
  '/boss/security-events': typeof BossSecurityEventsRoute
  '/boss/settings': typeof BossSettingsRoute
  '/boss/stream-queue': typeof BossStreamQueueRoute
  '/boss/telegram-setup': typeof BossTelegramSetupRoute
  '/boss/telegram-test': typeof BossTelegramTestRoute
  '/boss/todo': typeof BossTodoRoute
  '/boss/users': typeof BossUsersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/f/$slug': typeof FSlugRoute
  '/hub/$slug': typeof HubSlugRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/qa/hubs': typeof QaHubsRoute
  '/store/catalog': typeof StoreCatalogRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/vip/portals': typeof VipPortalsRouteWithChildren
  '/boss': typeof BossIndexRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/stream-m3u': typeof ApiPublicStreamM3uRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/boss/hubs/new': typeof BossHubsNewRoute
  '/vip/portals/$hub': typeof VipPortalsHubRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/boss/hubs/$id/edit': typeof BossHubsIdEditRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appealhub': typeof AppealhubRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/battlehub': typeof BattlehubRoute
  '/boss': typeof BossRouteWithChildren
  '/connect': typeof ConnectRoute
  '/connect-telegram': typeof ConnectTelegramRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formhub': typeof FormhubRoute
  '/history': typeof HistoryRoute
  '/jokes': typeof JokesRouteWithChildren
  '/letterhub': typeof LetterhubRoute
  '/music': typeof MusicRoute
  '/my-generations': typeof MyGenerationsRoute
  '/noticeboard': typeof NoticeboardRoute
  '/og-bot': typeof OgBotRoute
  '/portals': typeof PortalsRoute
  '/profile': typeof ProfileRoute
  '/reseller': typeof ResellerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRouteWithChildren
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vault-login': typeof VaultLoginRoute
  '/vip': typeof VipRouteWithChildren
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/account/passes': typeof AccountPassesRoute
  '/b/$slug': typeof BSlugRoute
  '/boss/ai-agent': typeof BossAiAgentRoute
  '/boss/alerts': typeof BossAlertsRoute
  '/boss/analytics': typeof BossAnalyticsRoute
  '/boss/analytics-setup': typeof BossAnalyticsSetupRoute
  '/boss/api-keys': typeof BossApiKeysRoute
  '/boss/audit-log': typeof BossAuditLogRoute
  '/boss/civility': typeof BossCivilityRoute
  '/boss/command-center': typeof BossCommandCenterRoute
  '/boss/contacts': typeof BossContactsRoute
  '/boss/content': typeof BossContentRoute
  '/boss/control-centre': typeof BossControlCentreRoute
  '/boss/denylist-audit': typeof BossDenylistAuditRoute
  '/boss/domain': typeof BossDomainRoute
  '/boss/domain-denylist': typeof BossDomainDenylistRoute
  '/boss/free-purchases': typeof BossFreePurchasesRoute
  '/boss/function-audit': typeof BossFunctionAuditRoute
  '/boss/function-grants': typeof BossFunctionGrantsRoute
  '/boss/function-ideas': typeof BossFunctionIdeasRoute
  '/boss/hubs': typeof BossHubsRouteWithChildren
  '/boss/infrastructure': typeof BossInfrastructureRoute
  '/boss/lexicon': typeof BossLexiconRoute
  '/boss/members': typeof BossMembersRoute
  '/boss/og-bot-memory': typeof BossOgBotMemoryRoute
  '/boss/og-passes': typeof BossOgPassesRoute
  '/boss/ops': typeof BossOpsRoute
  '/boss/overview': typeof BossOverviewRoute
  '/boss/portal-costs': typeof BossPortalCostsRoute
  '/boss/portal-usage': typeof BossPortalUsageRoute
  '/boss/portals': typeof BossPortalsRoute
  '/boss/power': typeof BossPowerRoute
  '/boss/pricing': typeof BossPricingRoute
  '/boss/promotions': typeof BossPromotionsRoute
  '/boss/publish-check': typeof BossPublishCheckRoute
  '/boss/realtime-denials': typeof BossRealtimeDenialsRoute
  '/boss/reseller-audit': typeof BossResellerAuditRoute
  '/boss/secrets-inventory': typeof BossSecretsInventoryRoute
  '/boss/security-events': typeof BossSecurityEventsRoute
  '/boss/settings': typeof BossSettingsRoute
  '/boss/stream-queue': typeof BossStreamQueueRoute
  '/boss/telegram-setup': typeof BossTelegramSetupRoute
  '/boss/telegram-test': typeof BossTelegramTestRoute
  '/boss/todo': typeof BossTodoRoute
  '/boss/users': typeof BossUsersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/f/$slug': typeof FSlugRoute
  '/hub/$slug': typeof HubSlugRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/qa/hubs': typeof QaHubsRoute
  '/store/catalog': typeof StoreCatalogRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/vip/portals': typeof VipPortalsRouteWithChildren
  '/boss/': typeof BossIndexRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/stream-m3u': typeof ApiPublicStreamM3uRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/boss/hubs/new': typeof BossHubsNewRoute
  '/vip/portals/$hub': typeof VipPortalsHubRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/boss/hubs/$id/edit': typeof BossHubsIdEditRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/appealhub'
    | '/auth'
    | '/battle'
    | '/battlehub'
    | '/boss'
    | '/connect'
    | '/connect-telegram'
    | '/console'
    | '/dashboard'
    | '/fleet'
    | '/forgot-password'
    | '/formhub'
    | '/history'
    | '/jokes'
    | '/letterhub'
    | '/music'
    | '/my-generations'
    | '/noticeboard'
    | '/og-bot'
    | '/portals'
    | '/profile'
    | '/reseller'
    | '/reset-password'
    | '/robots.txt'
    | '/settings'
    | '/sitemap'
    | '/sitemap.xml'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vault-login'
    | '/vip'
    | '/wallet'
    | '/welcome'
    | '/account/passes'
    | '/b/$slug'
    | '/boss/ai-agent'
    | '/boss/alerts'
    | '/boss/analytics'
    | '/boss/analytics-setup'
    | '/boss/api-keys'
    | '/boss/audit-log'
    | '/boss/civility'
    | '/boss/command-center'
    | '/boss/contacts'
    | '/boss/content'
    | '/boss/control-centre'
    | '/boss/denylist-audit'
    | '/boss/domain'
    | '/boss/domain-denylist'
    | '/boss/free-purchases'
    | '/boss/function-audit'
    | '/boss/function-grants'
    | '/boss/function-ideas'
    | '/boss/hubs'
    | '/boss/infrastructure'
    | '/boss/lexicon'
    | '/boss/members'
    | '/boss/og-bot-memory'
    | '/boss/og-passes'
    | '/boss/ops'
    | '/boss/overview'
    | '/boss/portal-costs'
    | '/boss/portal-usage'
    | '/boss/portals'
    | '/boss/power'
    | '/boss/pricing'
    | '/boss/promotions'
    | '/boss/publish-check'
    | '/boss/realtime-denials'
    | '/boss/reseller-audit'
    | '/boss/secrets-inventory'
    | '/boss/security-events'
    | '/boss/settings'
    | '/boss/stream-queue'
    | '/boss/telegram-setup'
    | '/boss/telegram-test'
    | '/boss/todo'
    | '/boss/users'
    | '/checkout/return'
    | '/f/$slug'
    | '/hub/$slug'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/qa/hubs'
    | '/store/catalog'
    | '/t/$slug'
    | '/td/$slug'
    | '/vip/portals'
    | '/boss/'
    | '/api/public/0g-orchestrator'
    | '/api/public/stream-m3u'
    | '/api/public/suno-webhook'
    | '/boss/hubs/new'
    | '/vip/portals/$hub'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/auth'
    | '/api/public/telegram/webhook'
    | '/boss/hubs/$id/edit'
    | '/api/public/fleet/webhook/$botId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/appealhub'
    | '/auth'
    | '/battle'
    | '/battlehub'
    | '/connect'
    | '/connect-telegram'
    | '/console'
    | '/dashboard'
    | '/fleet'
    | '/forgot-password'
    | '/formhub'
    | '/history'
    | '/jokes'
    | '/letterhub'
    | '/music'
    | '/my-generations'
    | '/noticeboard'
    | '/og-bot'
    | '/portals'
    | '/profile'
    | '/reseller'
    | '/reset-password'
    | '/robots.txt'
    | '/settings'
    | '/sitemap'
    | '/sitemap.xml'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vault-login'
    | '/vip'
    | '/wallet'
    | '/welcome'
    | '/account/passes'
    | '/b/$slug'
    | '/boss/ai-agent'
    | '/boss/alerts'
    | '/boss/analytics'
    | '/boss/analytics-setup'
    | '/boss/api-keys'
    | '/boss/audit-log'
    | '/boss/civility'
    | '/boss/command-center'
    | '/boss/contacts'
    | '/boss/content'
    | '/boss/control-centre'
    | '/boss/denylist-audit'
    | '/boss/domain'
    | '/boss/domain-denylist'
    | '/boss/free-purchases'
    | '/boss/function-audit'
    | '/boss/function-grants'
    | '/boss/function-ideas'
    | '/boss/hubs'
    | '/boss/infrastructure'
    | '/boss/lexicon'
    | '/boss/members'
    | '/boss/og-bot-memory'
    | '/boss/og-passes'
    | '/boss/ops'
    | '/boss/overview'
    | '/boss/portal-costs'
    | '/boss/portal-usage'
    | '/boss/portals'
    | '/boss/power'
    | '/boss/pricing'
    | '/boss/promotions'
    | '/boss/publish-check'
    | '/boss/realtime-denials'
    | '/boss/reseller-audit'
    | '/boss/secrets-inventory'
    | '/boss/security-events'
    | '/boss/settings'
    | '/boss/stream-queue'
    | '/boss/telegram-setup'
    | '/boss/telegram-test'
    | '/boss/todo'
    | '/boss/users'
    | '/checkout/return'
    | '/f/$slug'
    | '/hub/$slug'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/qa/hubs'
    | '/store/catalog'
    | '/t/$slug'
    | '/td/$slug'
    | '/vip/portals'
    | '/boss'
    | '/api/public/0g-orchestrator'
    | '/api/public/stream-m3u'
    | '/api/public/suno-webhook'
    | '/boss/hubs/new'
    | '/vip/portals/$hub'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/auth'
    | '/api/public/telegram/webhook'
    | '/boss/hubs/$id/edit'
    | '/api/public/fleet/webhook/$botId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/appealhub'
    | '/auth'
    | '/battle'
    | '/battlehub'
    | '/boss'
    | '/connect'
    | '/connect-telegram'
    | '/console'
    | '/dashboard'
    | '/fleet'
    | '/forgot-password'
    | '/formhub'
    | '/history'
    | '/jokes'
    | '/letterhub'
    | '/music'
    | '/my-generations'
    | '/noticeboard'
    | '/og-bot'
    | '/portals'
    | '/profile'
    | '/reseller'
    | '/reset-password'
    | '/robots.txt'
    | '/settings'
    | '/sitemap'
    | '/sitemap.xml'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vault-login'
    | '/vip'
    | '/wallet'
    | '/welcome'
    | '/account/passes'
    | '/b/$slug'
    | '/boss/ai-agent'
    | '/boss/alerts'
    | '/boss/analytics'
    | '/boss/analytics-setup'
    | '/boss/api-keys'
    | '/boss/audit-log'
    | '/boss/civility'
    | '/boss/command-center'
    | '/boss/contacts'
    | '/boss/content'
    | '/boss/control-centre'
    | '/boss/denylist-audit'
    | '/boss/domain'
    | '/boss/domain-denylist'
    | '/boss/free-purchases'
    | '/boss/function-audit'
    | '/boss/function-grants'
    | '/boss/function-ideas'
    | '/boss/hubs'
    | '/boss/infrastructure'
    | '/boss/lexicon'
    | '/boss/members'
    | '/boss/og-bot-memory'
    | '/boss/og-passes'
    | '/boss/ops'
    | '/boss/overview'
    | '/boss/portal-costs'
    | '/boss/portal-usage'
    | '/boss/portals'
    | '/boss/power'
    | '/boss/pricing'
    | '/boss/promotions'
    | '/boss/publish-check'
    | '/boss/realtime-denials'
    | '/boss/reseller-audit'
    | '/boss/secrets-inventory'
    | '/boss/security-events'
    | '/boss/settings'
    | '/boss/stream-queue'
    | '/boss/telegram-setup'
    | '/boss/telegram-test'
    | '/boss/todo'
    | '/boss/users'
    | '/checkout/return'
    | '/f/$slug'
    | '/hub/$slug'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/qa/hubs'
    | '/store/catalog'
    | '/t/$slug'
    | '/td/$slug'
    | '/vip/portals'
    | '/boss/'
    | '/api/public/0g-orchestrator'
    | '/api/public/stream-m3u'
    | '/api/public/suno-webhook'
    | '/boss/hubs/new'
    | '/vip/portals/$hub'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/auth'
    | '/api/public/telegram/webhook'
    | '/boss/hubs/$id/edit'
    | '/api/public/fleet/webhook/$botId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppealhubRoute: typeof AppealhubRoute
  AuthRoute: typeof AuthRoute
  BattleRoute: typeof BattleRoute
  BattlehubRoute: typeof BattlehubRoute
  BossRoute: typeof BossRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  ConnectTelegramRoute: typeof ConnectTelegramRoute
  ConsoleRoute: typeof ConsoleRoute
  DashboardRoute: typeof DashboardRoute
  FleetRoute: typeof FleetRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FormhubRoute: typeof FormhubRoute
  HistoryRoute: typeof HistoryRoute
  JokesRoute: typeof JokesRouteWithChildren
  LetterhubRoute: typeof LetterhubRoute
  MusicRoute: typeof MusicRoute
  MyGenerationsRoute: typeof MyGenerationsRoute
  NoticeboardRoute: typeof NoticeboardRoute
  OgBotRoute: typeof OgBotRoute
  PortalsRoute: typeof PortalsRoute
  ProfileRoute: typeof ProfileRoute
  ResellerRoute: typeof ResellerRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRouteWithChildren
  SyndicateRoute: typeof SyndicateRoute
  SyndicateOverlordRoute: typeof SyndicateOverlordRoute
  ToolsRoute: typeof ToolsRoute
  TradeRoute: typeof TradeRoute
  VaultLoginRoute: typeof VaultLoginRoute
  VipRoute: typeof VipRouteWithChildren
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  AccountPassesRoute: typeof AccountPassesRoute
  BSlugRoute: typeof BSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  FSlugRoute: typeof FSlugRoute
  HubSlugRoute: typeof HubSlugRoute
  MSlugRoute: typeof MSlugRoute
  PSlugRoute: typeof PSlugRoute
  QaHubsRoute: typeof QaHubsRoute
  TSlugRoute: typeof TSlugRoute
  TdSlugRoute: typeof TdSlugRoute
  ApiPublic0gOrchestratorRoute: typeof ApiPublic0gOrchestratorRoute
  ApiPublicStreamM3uRoute: typeof ApiPublicStreamM3uRoute
  ApiPublicSunoWebhookRoute: typeof ApiPublicSunoWebhookRoute
  ApiPublicHooksSyndicateTickRoute: typeof ApiPublicHooksSyndicateTickRoute
  ApiPublicHooksTelegramRemindersRoute: typeof ApiPublicHooksTelegramRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTelegramAuthRoute: typeof ApiPublicTelegramAuthRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicFleetWebhookBotIdRoute: typeof ApiPublicFleetWebhookBotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault-login': {
      id: '/vault-login'
      path: '/vault-login'
      fullPath: '/vault-login'
      preLoaderRoute: typeof VaultLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicate-overlord': {
      id: '/syndicate-overlord'
      path: '/syndicate-overlord'
      fullPath: '/syndicate-overlord'
      preLoaderRoute: typeof SyndicateOverlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicate': {
      id: '/syndicate'
      path: '/syndicate'
      fullPath: '/syndicate'
      preLoaderRoute: typeof SyndicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller': {
      id: '/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof ResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-bot': {
      id: '/og-bot'
      path: '/og-bot'
      fullPath: '/og-bot'
      preLoaderRoute: typeof OgBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticeboard': {
      id: '/noticeboard'
      path: '/noticeboard'
      fullPath: '/noticeboard'
      preLoaderRoute: typeof NoticeboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-generations': {
      id: '/my-generations'
      path: '/my-generations'
      fullPath: '/my-generations'
      preLoaderRoute: typeof MyGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letterhub': {
      id: '/letterhub'
      path: '/letterhub'
      fullPath: '/letterhub'
      preLoaderRoute: typeof LetterhubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes': {
      id: '/jokes'
      path: '/jokes'
      fullPath: '/jokes'
      preLoaderRoute: typeof JokesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formhub': {
      id: '/formhub'
      path: '/formhub'
      fullPath: '/formhub'
      preLoaderRoute: typeof FormhubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-telegram': {
      id: '/connect-telegram'
      path: '/connect-telegram'
      fullPath: '/connect-telegram'
      preLoaderRoute: typeof ConnectTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss': {
      id: '/boss'
      path: '/boss'
      fullPath: '/boss'
      preLoaderRoute: typeof BossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battlehub': {
      id: '/battlehub'
      path: '/battlehub'
      fullPath: '/battlehub'
      preLoaderRoute: typeof BattlehubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appealhub': {
      id: '/appealhub'
      path: '/appealhub'
      fullPath: '/appealhub'
      preLoaderRoute: typeof AppealhubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss/': {
      id: '/boss/'
      path: '/'
      fullPath: '/boss/'
      preLoaderRoute: typeof BossIndexRouteImport
      parentRoute: typeof BossRoute
    }
    '/vip/portals': {
      id: '/vip/portals'
      path: '/portals'
      fullPath: '/vip/portals'
      preLoaderRoute: typeof VipPortalsRouteImport
      parentRoute: typeof VipRoute
    }
    '/td/$slug': {
      id: '/td/$slug'
      path: '/td/$slug'
      fullPath: '/td/$slug'
      preLoaderRoute: typeof TdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/catalog': {
      id: '/store/catalog'
      path: '/catalog'
      fullPath: '/store/catalog'
      preLoaderRoute: typeof StoreCatalogRouteImport
      parentRoute: typeof StoreRoute
    }
    '/qa/hubs': {
      id: '/qa/hubs'
      path: '/qa/hubs'
      fullPath: '/qa/hubs'
      preLoaderRoute: typeof QaHubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes/portal': {
      id: '/jokes/portal'
      path: '/portal'
      fullPath: '/jokes/portal'
      preLoaderRoute: typeof JokesPortalRouteImport
      parentRoute: typeof JokesRoute
    }
    '/hub/$slug': {
      id: '/hub/$slug'
      path: '/hub/$slug'
      fullPath: '/hub/$slug'
      preLoaderRoute: typeof HubSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss/users': {
      id: '/boss/users'
      path: '/users'
      fullPath: '/boss/users'
      preLoaderRoute: typeof BossUsersRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/todo': {
      id: '/boss/todo'
      path: '/todo'
      fullPath: '/boss/todo'
      preLoaderRoute: typeof BossTodoRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/telegram-test': {
      id: '/boss/telegram-test'
      path: '/telegram-test'
      fullPath: '/boss/telegram-test'
      preLoaderRoute: typeof BossTelegramTestRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/telegram-setup': {
      id: '/boss/telegram-setup'
      path: '/telegram-setup'
      fullPath: '/boss/telegram-setup'
      preLoaderRoute: typeof BossTelegramSetupRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/stream-queue': {
      id: '/boss/stream-queue'
      path: '/stream-queue'
      fullPath: '/boss/stream-queue'
      preLoaderRoute: typeof BossStreamQueueRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/settings': {
      id: '/boss/settings'
      path: '/settings'
      fullPath: '/boss/settings'
      preLoaderRoute: typeof BossSettingsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/security-events': {
      id: '/boss/security-events'
      path: '/security-events'
      fullPath: '/boss/security-events'
      preLoaderRoute: typeof BossSecurityEventsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/secrets-inventory': {
      id: '/boss/secrets-inventory'
      path: '/secrets-inventory'
      fullPath: '/boss/secrets-inventory'
      preLoaderRoute: typeof BossSecretsInventoryRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/reseller-audit': {
      id: '/boss/reseller-audit'
      path: '/reseller-audit'
      fullPath: '/boss/reseller-audit'
      preLoaderRoute: typeof BossResellerAuditRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/realtime-denials': {
      id: '/boss/realtime-denials'
      path: '/realtime-denials'
      fullPath: '/boss/realtime-denials'
      preLoaderRoute: typeof BossRealtimeDenialsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/publish-check': {
      id: '/boss/publish-check'
      path: '/publish-check'
      fullPath: '/boss/publish-check'
      preLoaderRoute: typeof BossPublishCheckRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/promotions': {
      id: '/boss/promotions'
      path: '/promotions'
      fullPath: '/boss/promotions'
      preLoaderRoute: typeof BossPromotionsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/pricing': {
      id: '/boss/pricing'
      path: '/pricing'
      fullPath: '/boss/pricing'
      preLoaderRoute: typeof BossPricingRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/power': {
      id: '/boss/power'
      path: '/power'
      fullPath: '/boss/power'
      preLoaderRoute: typeof BossPowerRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/portals': {
      id: '/boss/portals'
      path: '/portals'
      fullPath: '/boss/portals'
      preLoaderRoute: typeof BossPortalsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/portal-usage': {
      id: '/boss/portal-usage'
      path: '/portal-usage'
      fullPath: '/boss/portal-usage'
      preLoaderRoute: typeof BossPortalUsageRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/portal-costs': {
      id: '/boss/portal-costs'
      path: '/portal-costs'
      fullPath: '/boss/portal-costs'
      preLoaderRoute: typeof BossPortalCostsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/overview': {
      id: '/boss/overview'
      path: '/overview'
      fullPath: '/boss/overview'
      preLoaderRoute: typeof BossOverviewRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/ops': {
      id: '/boss/ops'
      path: '/ops'
      fullPath: '/boss/ops'
      preLoaderRoute: typeof BossOpsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/og-passes': {
      id: '/boss/og-passes'
      path: '/og-passes'
      fullPath: '/boss/og-passes'
      preLoaderRoute: typeof BossOgPassesRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/og-bot-memory': {
      id: '/boss/og-bot-memory'
      path: '/og-bot-memory'
      fullPath: '/boss/og-bot-memory'
      preLoaderRoute: typeof BossOgBotMemoryRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/members': {
      id: '/boss/members'
      path: '/members'
      fullPath: '/boss/members'
      preLoaderRoute: typeof BossMembersRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/lexicon': {
      id: '/boss/lexicon'
      path: '/lexicon'
      fullPath: '/boss/lexicon'
      preLoaderRoute: typeof BossLexiconRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/infrastructure': {
      id: '/boss/infrastructure'
      path: '/infrastructure'
      fullPath: '/boss/infrastructure'
      preLoaderRoute: typeof BossInfrastructureRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/hubs': {
      id: '/boss/hubs'
      path: '/hubs'
      fullPath: '/boss/hubs'
      preLoaderRoute: typeof BossHubsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/function-ideas': {
      id: '/boss/function-ideas'
      path: '/function-ideas'
      fullPath: '/boss/function-ideas'
      preLoaderRoute: typeof BossFunctionIdeasRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/function-grants': {
      id: '/boss/function-grants'
      path: '/function-grants'
      fullPath: '/boss/function-grants'
      preLoaderRoute: typeof BossFunctionGrantsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/function-audit': {
      id: '/boss/function-audit'
      path: '/function-audit'
      fullPath: '/boss/function-audit'
      preLoaderRoute: typeof BossFunctionAuditRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/free-purchases': {
      id: '/boss/free-purchases'
      path: '/free-purchases'
      fullPath: '/boss/free-purchases'
      preLoaderRoute: typeof BossFreePurchasesRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/domain-denylist': {
      id: '/boss/domain-denylist'
      path: '/domain-denylist'
      fullPath: '/boss/domain-denylist'
      preLoaderRoute: typeof BossDomainDenylistRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/domain': {
      id: '/boss/domain'
      path: '/domain'
      fullPath: '/boss/domain'
      preLoaderRoute: typeof BossDomainRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/denylist-audit': {
      id: '/boss/denylist-audit'
      path: '/denylist-audit'
      fullPath: '/boss/denylist-audit'
      preLoaderRoute: typeof BossDenylistAuditRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/control-centre': {
      id: '/boss/control-centre'
      path: '/control-centre'
      fullPath: '/boss/control-centre'
      preLoaderRoute: typeof BossControlCentreRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/content': {
      id: '/boss/content'
      path: '/content'
      fullPath: '/boss/content'
      preLoaderRoute: typeof BossContentRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/contacts': {
      id: '/boss/contacts'
      path: '/contacts'
      fullPath: '/boss/contacts'
      preLoaderRoute: typeof BossContactsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/command-center': {
      id: '/boss/command-center'
      path: '/command-center'
      fullPath: '/boss/command-center'
      preLoaderRoute: typeof BossCommandCenterRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/civility': {
      id: '/boss/civility'
      path: '/civility'
      fullPath: '/boss/civility'
      preLoaderRoute: typeof BossCivilityRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/audit-log': {
      id: '/boss/audit-log'
      path: '/audit-log'
      fullPath: '/boss/audit-log'
      preLoaderRoute: typeof BossAuditLogRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/api-keys': {
      id: '/boss/api-keys'
      path: '/api-keys'
      fullPath: '/boss/api-keys'
      preLoaderRoute: typeof BossApiKeysRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/analytics-setup': {
      id: '/boss/analytics-setup'
      path: '/analytics-setup'
      fullPath: '/boss/analytics-setup'
      preLoaderRoute: typeof BossAnalyticsSetupRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/analytics': {
      id: '/boss/analytics'
      path: '/analytics'
      fullPath: '/boss/analytics'
      preLoaderRoute: typeof BossAnalyticsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/alerts': {
      id: '/boss/alerts'
      path: '/alerts'
      fullPath: '/boss/alerts'
      preLoaderRoute: typeof BossAlertsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/ai-agent': {
      id: '/boss/ai-agent'
      path: '/ai-agent'
      fullPath: '/boss/ai-agent'
      preLoaderRoute: typeof BossAiAgentRouteImport
      parentRoute: typeof BossRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/passes': {
      id: '/account/passes'
      path: '/account/passes'
      fullPath: '/account/passes'
      preLoaderRoute: typeof AccountPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip/portals/$hub': {
      id: '/vip/portals/$hub'
      path: '/$hub'
      fullPath: '/vip/portals/$hub'
      preLoaderRoute: typeof VipPortalsHubRouteImport
      parentRoute: typeof VipPortalsRoute
    }
    '/boss/hubs/new': {
      id: '/boss/hubs/new'
      path: '/new'
      fullPath: '/boss/hubs/new'
      preLoaderRoute: typeof BossHubsNewRouteImport
      parentRoute: typeof BossHubsRoute
    }
    '/api/public/suno-webhook': {
      id: '/api/public/suno-webhook'
      path: '/api/public/suno-webhook'
      fullPath: '/api/public/suno-webhook'
      preLoaderRoute: typeof ApiPublicSunoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream-m3u': {
      id: '/api/public/stream-m3u'
      path: '/api/public/stream-m3u'
      fullPath: '/api/public/stream-m3u'
      preLoaderRoute: typeof ApiPublicStreamM3uRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/0g-orchestrator': {
      id: '/api/public/0g-orchestrator'
      path: '/api/public/0g-orchestrator'
      fullPath: '/api/public/0g-orchestrator'
      preLoaderRoute: typeof ApiPublic0gOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss/hubs/$id/edit': {
      id: '/boss/hubs/$id/edit'
      path: '/$id/edit'
      fullPath: '/boss/hubs/$id/edit'
      preLoaderRoute: typeof BossHubsIdEditRouteImport
      parentRoute: typeof BossHubsRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/auth': {
      id: '/api/public/telegram/auth'
      path: '/api/public/telegram/auth'
      fullPath: '/api/public/telegram/auth'
      preLoaderRoute: typeof ApiPublicTelegramAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-reminders': {
      id: '/api/public/hooks/telegram-reminders'
      path: '/api/public/hooks/telegram-reminders'
      fullPath: '/api/public/hooks/telegram-reminders'
      preLoaderRoute: typeof ApiPublicHooksTelegramRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/syndicate-tick': {
      id: '/api/public/hooks/syndicate-tick'
      path: '/api/public/hooks/syndicate-tick'
      fullPath: '/api/public/hooks/syndicate-tick'
      preLoaderRoute: typeof ApiPublicHooksSyndicateTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fleet/webhook/$botId': {
      id: '/api/public/fleet/webhook/$botId'
      path: '/api/public/fleet/webhook/$botId'
      fullPath: '/api/public/fleet/webhook/$botId'
      preLoaderRoute: typeof ApiPublicFleetWebhookBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BossHubsRouteChildren {
  BossHubsNewRoute: typeof BossHubsNewRoute
  BossHubsIdEditRoute: typeof BossHubsIdEditRoute
}

const BossHubsRouteChildren: BossHubsRouteChildren = {
  BossHubsNewRoute: BossHubsNewRoute,
  BossHubsIdEditRoute: BossHubsIdEditRoute,
}

const BossHubsRouteWithChildren = BossHubsRoute._addFileChildren(
  BossHubsRouteChildren,
)

interface BossRouteChildren {
  BossAiAgentRoute: typeof BossAiAgentRoute
  BossAlertsRoute: typeof BossAlertsRoute
  BossAnalyticsRoute: typeof BossAnalyticsRoute
  BossAnalyticsSetupRoute: typeof BossAnalyticsSetupRoute
  BossApiKeysRoute: typeof BossApiKeysRoute
  BossAuditLogRoute: typeof BossAuditLogRoute
  BossCivilityRoute: typeof BossCivilityRoute
  BossCommandCenterRoute: typeof BossCommandCenterRoute
  BossContactsRoute: typeof BossContactsRoute
  BossContentRoute: typeof BossContentRoute
  BossControlCentreRoute: typeof BossControlCentreRoute
  BossDenylistAuditRoute: typeof BossDenylistAuditRoute
  BossDomainRoute: typeof BossDomainRoute
  BossDomainDenylistRoute: typeof BossDomainDenylistRoute
  BossFreePurchasesRoute: typeof BossFreePurchasesRoute
  BossFunctionAuditRoute: typeof BossFunctionAuditRoute
  BossFunctionGrantsRoute: typeof BossFunctionGrantsRoute
  BossFunctionIdeasRoute: typeof BossFunctionIdeasRoute
  BossHubsRoute: typeof BossHubsRouteWithChildren
  BossInfrastructureRoute: typeof BossInfrastructureRoute
  BossLexiconRoute: typeof BossLexiconRoute
  BossMembersRoute: typeof BossMembersRoute
  BossOgBotMemoryRoute: typeof BossOgBotMemoryRoute
  BossOgPassesRoute: typeof BossOgPassesRoute
  BossOpsRoute: typeof BossOpsRoute
  BossOverviewRoute: typeof BossOverviewRoute
  BossPortalCostsRoute: typeof BossPortalCostsRoute
  BossPortalUsageRoute: typeof BossPortalUsageRoute
  BossPortalsRoute: typeof BossPortalsRoute
  BossPowerRoute: typeof BossPowerRoute
  BossPricingRoute: typeof BossPricingRoute
  BossPromotionsRoute: typeof BossPromotionsRoute
  BossPublishCheckRoute: typeof BossPublishCheckRoute
  BossRealtimeDenialsRoute: typeof BossRealtimeDenialsRoute
  BossResellerAuditRoute: typeof BossResellerAuditRoute
  BossSecretsInventoryRoute: typeof BossSecretsInventoryRoute
  BossSecurityEventsRoute: typeof BossSecurityEventsRoute
  BossSettingsRoute: typeof BossSettingsRoute
  BossStreamQueueRoute: typeof BossStreamQueueRoute
  BossTelegramSetupRoute: typeof BossTelegramSetupRoute
  BossTelegramTestRoute: typeof BossTelegramTestRoute
  BossTodoRoute: typeof BossTodoRoute
  BossUsersRoute: typeof BossUsersRoute
  BossIndexRoute: typeof BossIndexRoute
}

const BossRouteChildren: BossRouteChildren = {
  BossAiAgentRoute: BossAiAgentRoute,
  BossAlertsRoute: BossAlertsRoute,
  BossAnalyticsRoute: BossAnalyticsRoute,
  BossAnalyticsSetupRoute: BossAnalyticsSetupRoute,
  BossApiKeysRoute: BossApiKeysRoute,
  BossAuditLogRoute: BossAuditLogRoute,
  BossCivilityRoute: BossCivilityRoute,
  BossCommandCenterRoute: BossCommandCenterRoute,
  BossContactsRoute: BossContactsRoute,
  BossContentRoute: BossContentRoute,
  BossControlCentreRoute: BossControlCentreRoute,
  BossDenylistAuditRoute: BossDenylistAuditRoute,
  BossDomainRoute: BossDomainRoute,
  BossDomainDenylistRoute: BossDomainDenylistRoute,
  BossFreePurchasesRoute: BossFreePurchasesRoute,
  BossFunctionAuditRoute: BossFunctionAuditRoute,
  BossFunctionGrantsRoute: BossFunctionGrantsRoute,
  BossFunctionIdeasRoute: BossFunctionIdeasRoute,
  BossHubsRoute: BossHubsRouteWithChildren,
  BossInfrastructureRoute: BossInfrastructureRoute,
  BossLexiconRoute: BossLexiconRoute,
  BossMembersRoute: BossMembersRoute,
  BossOgBotMemoryRoute: BossOgBotMemoryRoute,
  BossOgPassesRoute: BossOgPassesRoute,
  BossOpsRoute: BossOpsRoute,
  BossOverviewRoute: BossOverviewRoute,
  BossPortalCostsRoute: BossPortalCostsRoute,
  BossPortalUsageRoute: BossPortalUsageRoute,
  BossPortalsRoute: BossPortalsRoute,
  BossPowerRoute: BossPowerRoute,
  BossPricingRoute: BossPricingRoute,
  BossPromotionsRoute: BossPromotionsRoute,
  BossPublishCheckRoute: BossPublishCheckRoute,
  BossRealtimeDenialsRoute: BossRealtimeDenialsRoute,
  BossResellerAuditRoute: BossResellerAuditRoute,
  BossSecretsInventoryRoute: BossSecretsInventoryRoute,
  BossSecurityEventsRoute: BossSecurityEventsRoute,
  BossSettingsRoute: BossSettingsRoute,
  BossStreamQueueRoute: BossStreamQueueRoute,
  BossTelegramSetupRoute: BossTelegramSetupRoute,
  BossTelegramTestRoute: BossTelegramTestRoute,
  BossTodoRoute: BossTodoRoute,
  BossUsersRoute: BossUsersRoute,
  BossIndexRoute: BossIndexRoute,
}

const BossRouteWithChildren = BossRoute._addFileChildren(BossRouteChildren)

interface JokesRouteChildren {
  JokesPortalRoute: typeof JokesPortalRoute
}

const JokesRouteChildren: JokesRouteChildren = {
  JokesPortalRoute: JokesPortalRoute,
}

const JokesRouteWithChildren = JokesRoute._addFileChildren(JokesRouteChildren)

interface StoreRouteChildren {
  StoreCatalogRoute: typeof StoreCatalogRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreCatalogRoute: StoreCatalogRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface VipPortalsRouteChildren {
  VipPortalsHubRoute: typeof VipPortalsHubRoute
}

const VipPortalsRouteChildren: VipPortalsRouteChildren = {
  VipPortalsHubRoute: VipPortalsHubRoute,
}

const VipPortalsRouteWithChildren = VipPortalsRoute._addFileChildren(
  VipPortalsRouteChildren,
)

interface VipRouteChildren {
  VipPortalsRoute: typeof VipPortalsRouteWithChildren
}

const VipRouteChildren: VipRouteChildren = {
  VipPortalsRoute: VipPortalsRouteWithChildren,
}

const VipRouteWithChildren = VipRoute._addFileChildren(VipRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppealhubRoute: AppealhubRoute,
  AuthRoute: AuthRoute,
  BattleRoute: BattleRoute,
  BattlehubRoute: BattlehubRoute,
  BossRoute: BossRouteWithChildren,
  ConnectRoute: ConnectRoute,
  ConnectTelegramRoute: ConnectTelegramRoute,
  ConsoleRoute: ConsoleRoute,
  DashboardRoute: DashboardRoute,
  FleetRoute: FleetRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FormhubRoute: FormhubRoute,
  HistoryRoute: HistoryRoute,
  JokesRoute: JokesRouteWithChildren,
  LetterhubRoute: LetterhubRoute,
  MusicRoute: MusicRoute,
  MyGenerationsRoute: MyGenerationsRoute,
  NoticeboardRoute: NoticeboardRoute,
  OgBotRoute: OgBotRoute,
  PortalsRoute: PortalsRoute,
  ProfileRoute: ProfileRoute,
  ResellerRoute: ResellerRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRouteWithChildren,
  SyndicateRoute: SyndicateRoute,
  SyndicateOverlordRoute: SyndicateOverlordRoute,
  ToolsRoute: ToolsRoute,
  TradeRoute: TradeRoute,
  VaultLoginRoute: VaultLoginRoute,
  VipRoute: VipRouteWithChildren,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  AccountPassesRoute: AccountPassesRoute,
  BSlugRoute: BSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  FSlugRoute: FSlugRoute,
  HubSlugRoute: HubSlugRoute,
  MSlugRoute: MSlugRoute,
  PSlugRoute: PSlugRoute,
  QaHubsRoute: QaHubsRoute,
  TSlugRoute: TSlugRoute,
  TdSlugRoute: TdSlugRoute,
  ApiPublic0gOrchestratorRoute: ApiPublic0gOrchestratorRoute,
  ApiPublicStreamM3uRoute: ApiPublicStreamM3uRoute,
  ApiPublicSunoWebhookRoute: ApiPublicSunoWebhookRoute,
  ApiPublicHooksSyndicateTickRoute: ApiPublicHooksSyndicateTickRoute,
  ApiPublicHooksTelegramRemindersRoute: ApiPublicHooksTelegramRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTelegramAuthRoute: ApiPublicTelegramAuthRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicFleetWebhookBotIdRoute: ApiPublicFleetWebhookBotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
