/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VipRouteImport } from './routes/vip'
import { Route as VaultLoginRouteImport } from './routes/vault-login'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SyndicateOverlordRouteImport } from './routes/syndicate-overlord'
import { Route as SyndicateRouteImport } from './routes/syndicate'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResellerRouteImport } from './routes/reseller'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as NoticeboardRouteImport } from './routes/noticeboard'
import { Route as MusicRouteImport } from './routes/music'
import { Route as JokesRouteImport } from './routes/jokes'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as BossRouteImport } from './routes/boss'
import { Route as BattlehubRouteImport } from './routes/battlehub'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BossIndexRouteImport } from './routes/boss.index'
import { Route as TdSlugRouteImport } from './routes/td.$slug'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as StoreCatalogRouteImport } from './routes/store.catalog'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as JokesPortalRouteImport } from './routes/jokes.portal'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BossUsersRouteImport } from './routes/boss.users'
import { Route as BossStreamQueueRouteImport } from './routes/boss.stream-queue'
import { Route as BossSettingsRouteImport } from './routes/boss.settings'
import { Route as BossPricingRouteImport } from './routes/boss.pricing'
import { Route as BossPowerRouteImport } from './routes/boss.power'
import { Route as BossPortalsRouteImport } from './routes/boss.portals'
import { Route as BossPortalCostsRouteImport } from './routes/boss.portal-costs'
import { Route as BossOverviewRouteImport } from './routes/boss.overview'
import { Route as BossLexiconRouteImport } from './routes/boss.lexicon'
import { Route as BossHubsRouteImport } from './routes/boss.hubs'
import { Route as BossCivilityRouteImport } from './routes/boss.civility'
import { Route as BossAnalyticsRouteImport } from './routes/boss.analytics'
import { Route as BossAlertsRouteImport } from './routes/boss.alerts'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AccountPassesRouteImport } from './routes/account.passes'
import { Route as BossHubsNewRouteImport } from './routes/boss.hubs.new'
import { Route as ApiPublicSunoWebhookRouteImport } from './routes/api/public/suno-webhook'
import { Route as ApiPublic0gOrchestratorRouteImport } from './routes/api/public/0g-orchestrator'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTelegramRemindersRouteImport } from './routes/api/public/hooks/telegram-reminders'
import { Route as ApiPublicHooksSyndicateTickRouteImport } from './routes/api/public/hooks/syndicate-tick'
import { Route as ApiPublicFleetWebhookBotIdRouteImport } from './routes/api/public/fleet/webhook/$botId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultLoginRoute = VaultLoginRouteImport.update({
  id: '/vault-login',
  path: '/vault-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicateOverlordRoute = SyndicateOverlordRouteImport.update({
  id: '/syndicate-overlord',
  path: '/syndicate-overlord',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicateRoute = SyndicateRouteImport.update({
  id: '/syndicate',
  path: '/syndicate',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerRoute = ResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeboardRoute = NoticeboardRouteImport.update({
  id: '/noticeboard',
  path: '/noticeboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesRoute = JokesRouteImport.update({
  id: '/jokes',
  path: '/jokes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const BossRoute = BossRouteImport.update({
  id: '/boss',
  path: '/boss',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlehubRoute = BattlehubRouteImport.update({
  id: '/battlehub',
  path: '/battlehub',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BossIndexRoute = BossIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BossRoute,
} as any)
const TdSlugRoute = TdSlugRouteImport.update({
  id: '/td/$slug',
  path: '/td/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCatalogRoute = StoreCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => StoreRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesPortalRoute = JokesPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => JokesRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BossUsersRoute = BossUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BossRoute,
} as any)
const BossStreamQueueRoute = BossStreamQueueRouteImport.update({
  id: '/stream-queue',
  path: '/stream-queue',
  getParentRoute: () => BossRoute,
} as any)
const BossSettingsRoute = BossSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BossRoute,
} as any)
const BossPricingRoute = BossPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => BossRoute,
} as any)
const BossPowerRoute = BossPowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => BossRoute,
} as any)
const BossPortalsRoute = BossPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => BossRoute,
} as any)
const BossPortalCostsRoute = BossPortalCostsRouteImport.update({
  id: '/portal-costs',
  path: '/portal-costs',
  getParentRoute: () => BossRoute,
} as any)
const BossOverviewRoute = BossOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => BossRoute,
} as any)
const BossLexiconRoute = BossLexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => BossRoute,
} as any)
const BossHubsRoute = BossHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => BossRoute,
} as any)
const BossCivilityRoute = BossCivilityRouteImport.update({
  id: '/civility',
  path: '/civility',
  getParentRoute: () => BossRoute,
} as any)
const BossAnalyticsRoute = BossAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BossRoute,
} as any)
const BossAlertsRoute = BossAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => BossRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPassesRoute = AccountPassesRouteImport.update({
  id: '/account/passes',
  path: '/account/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const BossHubsNewRoute = BossHubsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BossHubsRoute,
} as any)
const ApiPublicSunoWebhookRoute = ApiPublicSunoWebhookRouteImport.update({
  id: '/api/public/suno-webhook',
  path: '/api/public/suno-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublic0gOrchestratorRoute = ApiPublic0gOrchestratorRouteImport.update({
  id: '/api/public/0g-orchestrator',
  path: '/api/public/0g-orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramRemindersRoute =
  ApiPublicHooksTelegramRemindersRouteImport.update({
    id: '/api/public/hooks/telegram-reminders',
    path: '/api/public/hooks/telegram-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyndicateTickRoute =
  ApiPublicHooksSyndicateTickRouteImport.update({
    id: '/api/public/hooks/syndicate-tick',
    path: '/api/public/hooks/syndicate-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFleetWebhookBotIdRoute =
  ApiPublicFleetWebhookBotIdRouteImport.update({
    id: '/api/public/fleet/webhook/$botId',
    path: '/api/public/fleet/webhook/$botId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/battlehub': typeof BattlehubRoute
  '/boss': typeof BossRouteWithChildren
  '/connect': typeof ConnectRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/jokes': typeof JokesRouteWithChildren
  '/music': typeof MusicRoute
  '/noticeboard': typeof NoticeboardRoute
  '/portals': typeof PortalsRoute
  '/profile': typeof ProfileRoute
  '/reseller': typeof ResellerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRouteWithChildren
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vault-login': typeof VaultLoginRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/account/passes': typeof AccountPassesRoute
  '/b/$slug': typeof BSlugRoute
  '/boss/alerts': typeof BossAlertsRoute
  '/boss/analytics': typeof BossAnalyticsRoute
  '/boss/civility': typeof BossCivilityRoute
  '/boss/hubs': typeof BossHubsRouteWithChildren
  '/boss/lexicon': typeof BossLexiconRoute
  '/boss/overview': typeof BossOverviewRoute
  '/boss/portal-costs': typeof BossPortalCostsRoute
  '/boss/portals': typeof BossPortalsRoute
  '/boss/power': typeof BossPowerRoute
  '/boss/pricing': typeof BossPricingRoute
  '/boss/settings': typeof BossSettingsRoute
  '/boss/stream-queue': typeof BossStreamQueueRoute
  '/boss/users': typeof BossUsersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/store/catalog': typeof StoreCatalogRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/boss/': typeof BossIndexRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/boss/hubs/new': typeof BossHubsNewRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/battlehub': typeof BattlehubRoute
  '/connect': typeof ConnectRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/jokes': typeof JokesRouteWithChildren
  '/music': typeof MusicRoute
  '/noticeboard': typeof NoticeboardRoute
  '/portals': typeof PortalsRoute
  '/profile': typeof ProfileRoute
  '/reseller': typeof ResellerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRouteWithChildren
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vault-login': typeof VaultLoginRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/account/passes': typeof AccountPassesRoute
  '/b/$slug': typeof BSlugRoute
  '/boss/alerts': typeof BossAlertsRoute
  '/boss/analytics': typeof BossAnalyticsRoute
  '/boss/civility': typeof BossCivilityRoute
  '/boss/hubs': typeof BossHubsRouteWithChildren
  '/boss/lexicon': typeof BossLexiconRoute
  '/boss/overview': typeof BossOverviewRoute
  '/boss/portal-costs': typeof BossPortalCostsRoute
  '/boss/portals': typeof BossPortalsRoute
  '/boss/power': typeof BossPowerRoute
  '/boss/pricing': typeof BossPricingRoute
  '/boss/settings': typeof BossSettingsRoute
  '/boss/stream-queue': typeof BossStreamQueueRoute
  '/boss/users': typeof BossUsersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/store/catalog': typeof StoreCatalogRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/boss': typeof BossIndexRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/boss/hubs/new': typeof BossHubsNewRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/battle': typeof BattleRoute
  '/battlehub': typeof BattlehubRoute
  '/boss': typeof BossRouteWithChildren
  '/connect': typeof ConnectRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/fleet': typeof FleetRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/jokes': typeof JokesRouteWithChildren
  '/music': typeof MusicRoute
  '/noticeboard': typeof NoticeboardRoute
  '/portals': typeof PortalsRoute
  '/profile': typeof ProfileRoute
  '/reseller': typeof ResellerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRouteWithChildren
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vault-login': typeof VaultLoginRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/account/passes': typeof AccountPassesRoute
  '/b/$slug': typeof BSlugRoute
  '/boss/alerts': typeof BossAlertsRoute
  '/boss/analytics': typeof BossAnalyticsRoute
  '/boss/civility': typeof BossCivilityRoute
  '/boss/hubs': typeof BossHubsRouteWithChildren
  '/boss/lexicon': typeof BossLexiconRoute
  '/boss/overview': typeof BossOverviewRoute
  '/boss/portal-costs': typeof BossPortalCostsRoute
  '/boss/portals': typeof BossPortalsRoute
  '/boss/power': typeof BossPowerRoute
  '/boss/pricing': typeof BossPricingRoute
  '/boss/settings': typeof BossSettingsRoute
  '/boss/stream-queue': typeof BossStreamQueueRoute
  '/boss/users': typeof BossUsersRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/store/catalog': typeof StoreCatalogRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/boss/': typeof BossIndexRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/boss/hubs/new': typeof BossHubsNewRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/hooks/telegram-reminders': typeof ApiPublicHooksTelegramRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/battle'
    | '/battlehub'
    | '/boss'
    | '/connect'
    | '/console'
    | '/dashboard'
    | '/fleet'
    | '/forgot-password'
    | '/history'
    | '/jokes'
    | '/music'
    | '/noticeboard'
    | '/portals'
    | '/profile'
    | '/reseller'
    | '/reset-password'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vault-login'
    | '/vip'
    | '/wallet'
    | '/welcome'
    | '/account/passes'
    | '/b/$slug'
    | '/boss/alerts'
    | '/boss/analytics'
    | '/boss/civility'
    | '/boss/hubs'
    | '/boss/lexicon'
    | '/boss/overview'
    | '/boss/portal-costs'
    | '/boss/portals'
    | '/boss/power'
    | '/boss/pricing'
    | '/boss/settings'
    | '/boss/stream-queue'
    | '/boss/users'
    | '/checkout/return'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/store/catalog'
    | '/t/$slug'
    | '/td/$slug'
    | '/boss/'
    | '/api/public/0g-orchestrator'
    | '/api/public/suno-webhook'
    | '/boss/hubs/new'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/fleet/webhook/$botId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/battle'
    | '/battlehub'
    | '/connect'
    | '/console'
    | '/dashboard'
    | '/fleet'
    | '/forgot-password'
    | '/history'
    | '/jokes'
    | '/music'
    | '/noticeboard'
    | '/portals'
    | '/profile'
    | '/reseller'
    | '/reset-password'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vault-login'
    | '/vip'
    | '/wallet'
    | '/welcome'
    | '/account/passes'
    | '/b/$slug'
    | '/boss/alerts'
    | '/boss/analytics'
    | '/boss/civility'
    | '/boss/hubs'
    | '/boss/lexicon'
    | '/boss/overview'
    | '/boss/portal-costs'
    | '/boss/portals'
    | '/boss/power'
    | '/boss/pricing'
    | '/boss/settings'
    | '/boss/stream-queue'
    | '/boss/users'
    | '/checkout/return'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/store/catalog'
    | '/t/$slug'
    | '/td/$slug'
    | '/boss'
    | '/api/public/0g-orchestrator'
    | '/api/public/suno-webhook'
    | '/boss/hubs/new'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/fleet/webhook/$botId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/battle'
    | '/battlehub'
    | '/boss'
    | '/connect'
    | '/console'
    | '/dashboard'
    | '/fleet'
    | '/forgot-password'
    | '/history'
    | '/jokes'
    | '/music'
    | '/noticeboard'
    | '/portals'
    | '/profile'
    | '/reseller'
    | '/reset-password'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vault-login'
    | '/vip'
    | '/wallet'
    | '/welcome'
    | '/account/passes'
    | '/b/$slug'
    | '/boss/alerts'
    | '/boss/analytics'
    | '/boss/civility'
    | '/boss/hubs'
    | '/boss/lexicon'
    | '/boss/overview'
    | '/boss/portal-costs'
    | '/boss/portals'
    | '/boss/power'
    | '/boss/pricing'
    | '/boss/settings'
    | '/boss/stream-queue'
    | '/boss/users'
    | '/checkout/return'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/store/catalog'
    | '/t/$slug'
    | '/td/$slug'
    | '/boss/'
    | '/api/public/0g-orchestrator'
    | '/api/public/suno-webhook'
    | '/boss/hubs/new'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/hooks/telegram-reminders'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/fleet/webhook/$botId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BattleRoute: typeof BattleRoute
  BattlehubRoute: typeof BattlehubRoute
  BossRoute: typeof BossRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  ConsoleRoute: typeof ConsoleRoute
  DashboardRoute: typeof DashboardRoute
  FleetRoute: typeof FleetRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  JokesRoute: typeof JokesRouteWithChildren
  MusicRoute: typeof MusicRoute
  NoticeboardRoute: typeof NoticeboardRoute
  PortalsRoute: typeof PortalsRoute
  ProfileRoute: typeof ProfileRoute
  ResellerRoute: typeof ResellerRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRouteWithChildren
  SyndicateRoute: typeof SyndicateRoute
  SyndicateOverlordRoute: typeof SyndicateOverlordRoute
  ToolsRoute: typeof ToolsRoute
  TradeRoute: typeof TradeRoute
  VaultLoginRoute: typeof VaultLoginRoute
  VipRoute: typeof VipRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  AccountPassesRoute: typeof AccountPassesRoute
  BSlugRoute: typeof BSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  MSlugRoute: typeof MSlugRoute
  PSlugRoute: typeof PSlugRoute
  TSlugRoute: typeof TSlugRoute
  TdSlugRoute: typeof TdSlugRoute
  ApiPublic0gOrchestratorRoute: typeof ApiPublic0gOrchestratorRoute
  ApiPublicSunoWebhookRoute: typeof ApiPublicSunoWebhookRoute
  ApiPublicHooksSyndicateTickRoute: typeof ApiPublicHooksSyndicateTickRoute
  ApiPublicHooksTelegramRemindersRoute: typeof ApiPublicHooksTelegramRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicFleetWebhookBotIdRoute: typeof ApiPublicFleetWebhookBotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault-login': {
      id: '/vault-login'
      path: '/vault-login'
      fullPath: '/vault-login'
      preLoaderRoute: typeof VaultLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicate-overlord': {
      id: '/syndicate-overlord'
      path: '/syndicate-overlord'
      fullPath: '/syndicate-overlord'
      preLoaderRoute: typeof SyndicateOverlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicate': {
      id: '/syndicate'
      path: '/syndicate'
      fullPath: '/syndicate'
      preLoaderRoute: typeof SyndicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller': {
      id: '/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof ResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticeboard': {
      id: '/noticeboard'
      path: '/noticeboard'
      fullPath: '/noticeboard'
      preLoaderRoute: typeof NoticeboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes': {
      id: '/jokes'
      path: '/jokes'
      fullPath: '/jokes'
      preLoaderRoute: typeof JokesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss': {
      id: '/boss'
      path: '/boss'
      fullPath: '/boss'
      preLoaderRoute: typeof BossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battlehub': {
      id: '/battlehub'
      path: '/battlehub'
      fullPath: '/battlehub'
      preLoaderRoute: typeof BattlehubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss/': {
      id: '/boss/'
      path: '/'
      fullPath: '/boss/'
      preLoaderRoute: typeof BossIndexRouteImport
      parentRoute: typeof BossRoute
    }
    '/td/$slug': {
      id: '/td/$slug'
      path: '/td/$slug'
      fullPath: '/td/$slug'
      preLoaderRoute: typeof TdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/catalog': {
      id: '/store/catalog'
      path: '/catalog'
      fullPath: '/store/catalog'
      preLoaderRoute: typeof StoreCatalogRouteImport
      parentRoute: typeof StoreRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes/portal': {
      id: '/jokes/portal'
      path: '/portal'
      fullPath: '/jokes/portal'
      preLoaderRoute: typeof JokesPortalRouteImport
      parentRoute: typeof JokesRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss/users': {
      id: '/boss/users'
      path: '/users'
      fullPath: '/boss/users'
      preLoaderRoute: typeof BossUsersRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/stream-queue': {
      id: '/boss/stream-queue'
      path: '/stream-queue'
      fullPath: '/boss/stream-queue'
      preLoaderRoute: typeof BossStreamQueueRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/settings': {
      id: '/boss/settings'
      path: '/settings'
      fullPath: '/boss/settings'
      preLoaderRoute: typeof BossSettingsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/pricing': {
      id: '/boss/pricing'
      path: '/pricing'
      fullPath: '/boss/pricing'
      preLoaderRoute: typeof BossPricingRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/power': {
      id: '/boss/power'
      path: '/power'
      fullPath: '/boss/power'
      preLoaderRoute: typeof BossPowerRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/portals': {
      id: '/boss/portals'
      path: '/portals'
      fullPath: '/boss/portals'
      preLoaderRoute: typeof BossPortalsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/portal-costs': {
      id: '/boss/portal-costs'
      path: '/portal-costs'
      fullPath: '/boss/portal-costs'
      preLoaderRoute: typeof BossPortalCostsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/overview': {
      id: '/boss/overview'
      path: '/overview'
      fullPath: '/boss/overview'
      preLoaderRoute: typeof BossOverviewRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/lexicon': {
      id: '/boss/lexicon'
      path: '/lexicon'
      fullPath: '/boss/lexicon'
      preLoaderRoute: typeof BossLexiconRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/hubs': {
      id: '/boss/hubs'
      path: '/hubs'
      fullPath: '/boss/hubs'
      preLoaderRoute: typeof BossHubsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/civility': {
      id: '/boss/civility'
      path: '/civility'
      fullPath: '/boss/civility'
      preLoaderRoute: typeof BossCivilityRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/analytics': {
      id: '/boss/analytics'
      path: '/analytics'
      fullPath: '/boss/analytics'
      preLoaderRoute: typeof BossAnalyticsRouteImport
      parentRoute: typeof BossRoute
    }
    '/boss/alerts': {
      id: '/boss/alerts'
      path: '/alerts'
      fullPath: '/boss/alerts'
      preLoaderRoute: typeof BossAlertsRouteImport
      parentRoute: typeof BossRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/passes': {
      id: '/account/passes'
      path: '/account/passes'
      fullPath: '/account/passes'
      preLoaderRoute: typeof AccountPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss/hubs/new': {
      id: '/boss/hubs/new'
      path: '/new'
      fullPath: '/boss/hubs/new'
      preLoaderRoute: typeof BossHubsNewRouteImport
      parentRoute: typeof BossHubsRoute
    }
    '/api/public/suno-webhook': {
      id: '/api/public/suno-webhook'
      path: '/api/public/suno-webhook'
      fullPath: '/api/public/suno-webhook'
      preLoaderRoute: typeof ApiPublicSunoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/0g-orchestrator': {
      id: '/api/public/0g-orchestrator'
      path: '/api/public/0g-orchestrator'
      fullPath: '/api/public/0g-orchestrator'
      preLoaderRoute: typeof ApiPublic0gOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-reminders': {
      id: '/api/public/hooks/telegram-reminders'
      path: '/api/public/hooks/telegram-reminders'
      fullPath: '/api/public/hooks/telegram-reminders'
      preLoaderRoute: typeof ApiPublicHooksTelegramRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/syndicate-tick': {
      id: '/api/public/hooks/syndicate-tick'
      path: '/api/public/hooks/syndicate-tick'
      fullPath: '/api/public/hooks/syndicate-tick'
      preLoaderRoute: typeof ApiPublicHooksSyndicateTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fleet/webhook/$botId': {
      id: '/api/public/fleet/webhook/$botId'
      path: '/api/public/fleet/webhook/$botId'
      fullPath: '/api/public/fleet/webhook/$botId'
      preLoaderRoute: typeof ApiPublicFleetWebhookBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BossHubsRouteChildren {
  BossHubsNewRoute: typeof BossHubsNewRoute
}

const BossHubsRouteChildren: BossHubsRouteChildren = {
  BossHubsNewRoute: BossHubsNewRoute,
}

const BossHubsRouteWithChildren = BossHubsRoute._addFileChildren(
  BossHubsRouteChildren,
)

interface BossRouteChildren {
  BossAlertsRoute: typeof BossAlertsRoute
  BossAnalyticsRoute: typeof BossAnalyticsRoute
  BossCivilityRoute: typeof BossCivilityRoute
  BossHubsRoute: typeof BossHubsRouteWithChildren
  BossLexiconRoute: typeof BossLexiconRoute
  BossOverviewRoute: typeof BossOverviewRoute
  BossPortalCostsRoute: typeof BossPortalCostsRoute
  BossPortalsRoute: typeof BossPortalsRoute
  BossPowerRoute: typeof BossPowerRoute
  BossPricingRoute: typeof BossPricingRoute
  BossSettingsRoute: typeof BossSettingsRoute
  BossStreamQueueRoute: typeof BossStreamQueueRoute
  BossUsersRoute: typeof BossUsersRoute
  BossIndexRoute: typeof BossIndexRoute
}

const BossRouteChildren: BossRouteChildren = {
  BossAlertsRoute: BossAlertsRoute,
  BossAnalyticsRoute: BossAnalyticsRoute,
  BossCivilityRoute: BossCivilityRoute,
  BossHubsRoute: BossHubsRouteWithChildren,
  BossLexiconRoute: BossLexiconRoute,
  BossOverviewRoute: BossOverviewRoute,
  BossPortalCostsRoute: BossPortalCostsRoute,
  BossPortalsRoute: BossPortalsRoute,
  BossPowerRoute: BossPowerRoute,
  BossPricingRoute: BossPricingRoute,
  BossSettingsRoute: BossSettingsRoute,
  BossStreamQueueRoute: BossStreamQueueRoute,
  BossUsersRoute: BossUsersRoute,
  BossIndexRoute: BossIndexRoute,
}

const BossRouteWithChildren = BossRoute._addFileChildren(BossRouteChildren)

interface JokesRouteChildren {
  JokesPortalRoute: typeof JokesPortalRoute
}

const JokesRouteChildren: JokesRouteChildren = {
  JokesPortalRoute: JokesPortalRoute,
}

const JokesRouteWithChildren = JokesRoute._addFileChildren(JokesRouteChildren)

interface StoreRouteChildren {
  StoreCatalogRoute: typeof StoreCatalogRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreCatalogRoute: StoreCatalogRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BattleRoute: BattleRoute,
  BattlehubRoute: BattlehubRoute,
  BossRoute: BossRouteWithChildren,
  ConnectRoute: ConnectRoute,
  ConsoleRoute: ConsoleRoute,
  DashboardRoute: DashboardRoute,
  FleetRoute: FleetRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  JokesRoute: JokesRouteWithChildren,
  MusicRoute: MusicRoute,
  NoticeboardRoute: NoticeboardRoute,
  PortalsRoute: PortalsRoute,
  ProfileRoute: ProfileRoute,
  ResellerRoute: ResellerRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRouteWithChildren,
  SyndicateRoute: SyndicateRoute,
  SyndicateOverlordRoute: SyndicateOverlordRoute,
  ToolsRoute: ToolsRoute,
  TradeRoute: TradeRoute,
  VaultLoginRoute: VaultLoginRoute,
  VipRoute: VipRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  AccountPassesRoute: AccountPassesRoute,
  BSlugRoute: BSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  MSlugRoute: MSlugRoute,
  PSlugRoute: PSlugRoute,
  TSlugRoute: TSlugRoute,
  TdSlugRoute: TdSlugRoute,
  ApiPublic0gOrchestratorRoute: ApiPublic0gOrchestratorRoute,
  ApiPublicSunoWebhookRoute: ApiPublicSunoWebhookRoute,
  ApiPublicHooksSyndicateTickRoute: ApiPublicHooksSyndicateTickRoute,
  ApiPublicHooksTelegramRemindersRoute: ApiPublicHooksTelegramRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicFleetWebhookBotIdRoute: ApiPublicFleetWebhookBotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
