/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SyndicateOverlordRouteImport } from './routes/syndicate-overlord'
import { Route as SyndicateRouteImport } from './routes/syndicate'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MusicRouteImport } from './routes/music'
import { Route as JokesRouteImport } from './routes/jokes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TdSlugRouteImport } from './routes/td.$slug'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as JokesPortalRouteImport } from './routes/jokes.portal'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPublicSunoWebhookRouteImport } from './routes/api/public/suno-webhook'
import { Route as ApiPublic0gOrchestratorRouteImport } from './routes/api/public/0g-orchestrator'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksSyndicateTickRouteImport } from './routes/api/public/hooks/syndicate-tick'
import { Route as ApiPublicFleetWebhookBotIdRouteImport } from './routes/api/public/fleet/webhook/$botId'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicateOverlordRoute = SyndicateOverlordRouteImport.update({
  id: '/syndicate-overlord',
  path: '/syndicate-overlord',
  getParentRoute: () => rootRouteImport,
} as any)
const SyndicateRoute = SyndicateRouteImport.update({
  id: '/syndicate',
  path: '/syndicate',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesRoute = JokesRouteImport.update({
  id: '/jokes',
  path: '/jokes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TdSlugRoute = TdSlugRouteImport.update({
  id: '/td/$slug',
  path: '/td/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesPortalRoute = JokesPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => JokesRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSunoWebhookRoute = ApiPublicSunoWebhookRouteImport.update({
  id: '/api/public/suno-webhook',
  path: '/api/public/suno-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublic0gOrchestratorRoute = ApiPublic0gOrchestratorRouteImport.update({
  id: '/api/public/0g-orchestrator',
  path: '/api/public/0g-orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyndicateTickRoute =
  ApiPublicHooksSyndicateTickRouteImport.update({
    id: '/api/public/hooks/syndicate-tick',
    path: '/api/public/hooks/syndicate-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFleetWebhookBotIdRoute =
  ApiPublicFleetWebhookBotIdRouteImport.update({
    id: '/api/public/fleet/webhook/$botId',
    path: '/api/public/fleet/webhook/$botId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/jokes': typeof JokesRouteWithChildren
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vip': typeof VipRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/jokes': typeof JokesRouteWithChildren
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vip': typeof VipRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/jokes': typeof JokesRouteWithChildren
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/syndicate': typeof SyndicateRoute
  '/syndicate-overlord': typeof SyndicateOverlordRoute
  '/tools': typeof ToolsRoute
  '/trade': typeof TradeRoute
  '/vip': typeof VipRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/jokes/portal': typeof JokesPortalRoute
  '/m/$slug': typeof MSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/td/$slug': typeof TdSlugRoute
  '/api/public/0g-orchestrator': typeof ApiPublic0gOrchestratorRoute
  '/api/public/suno-webhook': typeof ApiPublicSunoWebhookRoute
  '/api/public/hooks/syndicate-tick': typeof ApiPublicHooksSyndicateTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/fleet/webhook/$botId': typeof ApiPublicFleetWebhookBotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/connect'
    | '/dashboard'
    | '/jokes'
    | '/music'
    | '/profile'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vip'
    | '/checkout/return'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/t/$slug'
    | '/td/$slug'
    | '/api/public/0g-orchestrator'
    | '/api/public/suno-webhook'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/payments/webhook'
    | '/api/public/fleet/webhook/$botId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/connect'
    | '/dashboard'
    | '/jokes'
    | '/music'
    | '/profile'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vip'
    | '/checkout/return'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/t/$slug'
    | '/td/$slug'
    | '/api/public/0g-orchestrator'
    | '/api/public/suno-webhook'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/payments/webhook'
    | '/api/public/fleet/webhook/$botId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/connect'
    | '/dashboard'
    | '/jokes'
    | '/music'
    | '/profile'
    | '/store'
    | '/syndicate'
    | '/syndicate-overlord'
    | '/tools'
    | '/trade'
    | '/vip'
    | '/checkout/return'
    | '/jokes/portal'
    | '/m/$slug'
    | '/p/$slug'
    | '/t/$slug'
    | '/td/$slug'
    | '/api/public/0g-orchestrator'
    | '/api/public/suno-webhook'
    | '/api/public/hooks/syndicate-tick'
    | '/api/public/payments/webhook'
    | '/api/public/fleet/webhook/$botId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  JokesRoute: typeof JokesRouteWithChildren
  MusicRoute: typeof MusicRoute
  ProfileRoute: typeof ProfileRoute
  StoreRoute: typeof StoreRoute
  SyndicateRoute: typeof SyndicateRoute
  SyndicateOverlordRoute: typeof SyndicateOverlordRoute
  ToolsRoute: typeof ToolsRoute
  TradeRoute: typeof TradeRoute
  VipRoute: typeof VipRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  MSlugRoute: typeof MSlugRoute
  PSlugRoute: typeof PSlugRoute
  TSlugRoute: typeof TSlugRoute
  TdSlugRoute: typeof TdSlugRoute
  ApiPublic0gOrchestratorRoute: typeof ApiPublic0gOrchestratorRoute
  ApiPublicSunoWebhookRoute: typeof ApiPublicSunoWebhookRoute
  ApiPublicHooksSyndicateTickRoute: typeof ApiPublicHooksSyndicateTickRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicFleetWebhookBotIdRoute: typeof ApiPublicFleetWebhookBotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicate-overlord': {
      id: '/syndicate-overlord'
      path: '/syndicate-overlord'
      fullPath: '/syndicate-overlord'
      preLoaderRoute: typeof SyndicateOverlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syndicate': {
      id: '/syndicate'
      path: '/syndicate'
      fullPath: '/syndicate'
      preLoaderRoute: typeof SyndicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes': {
      id: '/jokes'
      path: '/jokes'
      fullPath: '/jokes'
      preLoaderRoute: typeof JokesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/td/$slug': {
      id: '/td/$slug'
      path: '/td/$slug'
      fullPath: '/td/$slug'
      preLoaderRoute: typeof TdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes/portal': {
      id: '/jokes/portal'
      path: '/portal'
      fullPath: '/jokes/portal'
      preLoaderRoute: typeof JokesPortalRouteImport
      parentRoute: typeof JokesRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/suno-webhook': {
      id: '/api/public/suno-webhook'
      path: '/api/public/suno-webhook'
      fullPath: '/api/public/suno-webhook'
      preLoaderRoute: typeof ApiPublicSunoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/0g-orchestrator': {
      id: '/api/public/0g-orchestrator'
      path: '/api/public/0g-orchestrator'
      fullPath: '/api/public/0g-orchestrator'
      preLoaderRoute: typeof ApiPublic0gOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/syndicate-tick': {
      id: '/api/public/hooks/syndicate-tick'
      path: '/api/public/hooks/syndicate-tick'
      fullPath: '/api/public/hooks/syndicate-tick'
      preLoaderRoute: typeof ApiPublicHooksSyndicateTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fleet/webhook/$botId': {
      id: '/api/public/fleet/webhook/$botId'
      path: '/api/public/fleet/webhook/$botId'
      fullPath: '/api/public/fleet/webhook/$botId'
      preLoaderRoute: typeof ApiPublicFleetWebhookBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JokesRouteChildren {
  JokesPortalRoute: typeof JokesPortalRoute
}

const JokesRouteChildren: JokesRouteChildren = {
  JokesPortalRoute: JokesPortalRoute,
}

const JokesRouteWithChildren = JokesRoute._addFileChildren(JokesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  JokesRoute: JokesRouteWithChildren,
  MusicRoute: MusicRoute,
  ProfileRoute: ProfileRoute,
  StoreRoute: StoreRoute,
  SyndicateRoute: SyndicateRoute,
  SyndicateOverlordRoute: SyndicateOverlordRoute,
  ToolsRoute: ToolsRoute,
  TradeRoute: TradeRoute,
  VipRoute: VipRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  MSlugRoute: MSlugRoute,
  PSlugRoute: PSlugRoute,
  TSlugRoute: TSlugRoute,
  TdSlugRoute: TdSlugRoute,
  ApiPublic0gOrchestratorRoute: ApiPublic0gOrchestratorRoute,
  ApiPublicSunoWebhookRoute: ApiPublicSunoWebhookRoute,
  ApiPublicHooksSyndicateTickRoute: ApiPublicHooksSyndicateTickRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicFleetWebhookBotIdRoute: ApiPublicFleetWebhookBotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
