
UPDATE public.portals
SET jokes = to_jsonb(ARRAY[
  'My dad''s belt has seen more action than Bollywood''s entire stunt industry.',
  'Indian parents don''t need therapists. They have neighbours to compare you with.',
  'My mum can detect a single grain of sugar in chai from three rooms away but can''t hear me ask for the Wi-Fi password.',
  'Arranged marriage is just Tinder with aunties as the algorithm.',
  'My CV says "fluent in English". My family WhatsApp group says otherwise — it''s 90% forwarded good-morning flowers.',
  'In India, traffic lights are decoration and indicators are a personal opinion.',
  'My uncle survived two heart attacks, three bypasses, and one bite of unsalted food. The food nearly finished him.',
  'Sharma ji ka beta isn''t a person. He''s a fucking psychological weapon.',
  'I told my mum I wanted space. She brought more relatives.',
  'Indian weddings: three days of chaos so two strangers can argue for forty years.',
  'My dad''s reaction to me crying as a kid: "I''ll give you a real reason to cry." Bro, that''s called escalation, not parenting.',
  'Desi parents'' love language is leaving the last piece of food on the plate and watching you starve out of politeness.',
  'My nani''s remedy for cancer is haldi doodh. Her remedy for a broken leg is also haldi doodh. Honestly, she might be onto something.',
  'In India, "five minutes" is a unit of time between thirty minutes and never.',
  'I said I''m vegan in front of my Punjabi uncle. He laughed so hard he choked on a samosa, then fed me butter chicken at gunpoint.',
  'My family planned my career, my marriage, and my funeral. I just have to show up on time, which is the one thing they didn''t plan.',
  'The Indian economy is like our family WhatsApp group: always loud, always on fire, and nobody knows who the fuck started it.',
  'Ghar ki daal is healthy. Ghar ki gaali is healthier.',
  'Indian dads communicate in three modes: silent, scolding, and "beta, get me water from the kitchen that''s literally two feet from your face".',
  'My cousin became a doctor. My other cousin became an engineer. I became the family''s cautionary tale and honestly, the role pays in screen time.',
  'Bollywood logic: hero gets shot twelve times, dances, sings, slaps four goons, marries the girl. Me: stub my toe and call in sick for a week.',
  'My mum''s "thoda sa khana" is enough to feed a small village and a goat.',
  'Indian roads have three lanes: left, right, and "fuck it, we''ll make our own".',
  'My uncle drinks whisky like it''s water and water like it''s an insult.',
  'Punjabi weddings don''t end. They just relocate.',
  'My dad''s WhatsApp DP has been the same lotus flower since 2014. His personality is also the same lotus flower since 2014.',
  'In a desi household, asking for privacy is treated like asking for a kidney.',
  'My grandma''s blessings come with a side of guilt and instructions on how to use it.',
  'Indians don''t queue. We just stand very close to whoever''s in front and pretend gravity is doing the rest.',
  'I tried explaining "mental health" to my dad. He prescribed pushups and shut the fuck up.',
  'My mum''s phone has 40,000 forwarded photos and zero of me.',
  'Desi parents brag about your salary to relatives and then ask you for money the same evening.',
  'Indian autorickshaw meters are like crypto: nobody understands them and somehow you''re always poorer at the end.',
  'My nani thinks Wi-Fi is a person. Honestly, given how much she yells at it, Wi-Fi has earned that promotion.',
  'My mum''s definition of "we have food at home" is three onions, half a lemon, and the will to suffer.',
  'In India, the word "adjust" has built more roads, marriages, and trauma than any government scheme.',
  'My family''s idea of mental rest is a 14-hour bus ride to a temple where you stand in a queue for 8 hours to see a god for 4 seconds.',
  'My uncle gave me life advice while smoking a beedi and choking on it. The advice was "don''t smoke".',
  'Indian summers are so hot the pigeons file a complaint and then forget the address.',
  'My dad''s WhatsApp forwards have given me more anxiety than my entire job.',
  'The Indian middle class lives in eternal fear of two things: cancer and the neighbours finding out anything.',
  'My mum''s "I''m fine" has more layers than the Mahabharat.',
  'Cricket in India isn''t a sport. It''s a personality disorder.',
  'My dad''s remote control technique is just pressing every button harder until the TV submits.',
  'Indian aunties don''t gossip. They run an unlicensed intelligence agency over chai.',
  'My nani lived through famine, partition, and three wars. I cried because Uber Eats was late.'
]::text[])
WHERE slug = 'proper-indian-comedy';
